/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OioyTMr4KqB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function AdminPanel() {
  return (
    (<div className="max-w-4xl mx-auto my-10 p-8 bg-white shadow rounded-lg">
      <h1 className="text-4xl font-bold mb-10">Welcome, Admin!</h1>
      <div className="space-y-8">
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 1, 2024</h2>
          <div className="flex items-center justify-between mb-2">
            <p className="text-lg">Class 1 - Venue A</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-lg">Class 2 - Venue B</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 2, 2024</h2>
          <div className="flex items-center justify-between mb-2">
            <p className="text-lg">Class 3 - Venue C</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-lg">Class 4 - Venue D</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 3, 2024</h2>
          <div className="flex items-center justify-between mb-2">
            <p className="text-lg">Class 5 - Venue E</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-lg">Class 6 - Venue F</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 4, 2024</h2>
          <div className="flex items-center justify-between mb-2">
            <p className="text-lg">Class 7 - Venue G</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-lg">Class 8 - Venue H</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 5, 2024</h2>
          <div className="flex items-center justify-between mb-2">
            <p className="text-lg">Class 9 - Venue I</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-lg">Class 10 - Venue J</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 6, 2024</h2>
          <div className="flex items-center justify-between mb-2">
            <p className="text-lg">Class 11 - Venue K</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-lg">Class 12 - Venue L</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 7, 2024</h2>
          <div className="flex items-center justify-between mb-2">
            <p className="text-lg">Class 13 - Venue M</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <p className="text-lg">Class 14 - Venue N</p>
            <div className="flex space-x-2">
              <Button variant="outline">Change Venue</Button>
              <Button variant="destructive">Cancel Class</Button>
            </div>
          </div>
        </div>
      </div>
    </div>)
  );
}
