/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Iw9nflD2pFD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function EventList() {
  return (
    (<div className="max-w-4xl mx-auto my-20 p-8 bg-white shadow rounded-lg">
      <div className="flex items-center justify-center mb-10">
        <h1 className="text-4xl font-bold">Hey Student!</h1>
        <h2 className="text-2xl font-semibold ml-4">Here are your upcoming events</h2>
      </div>
      <div className="space-y-8">
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 6, 2024</h2>
          <div className="flex items-center justify-between">
            <div
              className="flex-1 rounded-md border border-gray-200 px-4 py-4 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 h-32 dark:border-gray-800">
                </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 7, 2024</h2>
          <div className="flex items-center justify-between">
            <div
              className="flex-1 rounded-md border border-gray-200 px-4 py-4 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 h-32 dark:border-gray-800" >

             </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 8, 2024</h2>
          <div className="flex items-center justify-between">
            <div
              className="flex-1 rounded-md border border-gray-200 px-4 py-4 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 h-32 dark:border-gray-800" >
               <span className="text-2xl">CyptoQuest - Blockchain Club</span> 
                </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 9, 2024</h2>
          <div className="flex items-center justify-between">
            <div
              className="flex-1 rounded-md border border-gray-200 px-4 py-4 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 h-32 dark:border-gray-800"/>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 10, 2024</h2>
          <div className="flex items-center justify-between">
            <div
              className="flex-1 rounded-md border border-gray-200 px-4 py-4 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 h-32 dark:border-gray-800" />
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 11, 2024</h2>
          <div className="flex items-center justify-between">
            <div
              className="flex-1 rounded-md border border-gray-200 px-4 py-4 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 h-32 dark:border-gray-800" />
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 12, 2024</h2>
          <div className="flex items-center justify-between">
            <div
              className="flex-1 rounded-md border border-gray-200 px-4 py-4 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 h-32 dark:border-gray-800" >
                <span className="text-2xl">GameFlix - IOS Club</span>
                </div>
          </div>
        </div>
      </div>
    </div>)
  );
}
