/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VZRHqS3ItW4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function MessMenu() {
  return (
    (<Table className="min-w-full">
      <TableHeader>
        <TableRow>
          <TableHead className="text-gray-500 dark:text-gray-400">Meal/Time</TableHead>
          <TableHead className="text-blue-500 dark:text-blue-400">Monday</TableHead>
          <TableHead className="text-blue-500 dark:text-blue-400">Tuesday</TableHead>
          <TableHead className="text-blue-500 dark:text-blue-400">Wednesday</TableHead>
          <TableHead className="text-blue-500 dark:text-blue-400">Thursday</TableHead>
          <TableHead className="text-blue-500 dark:text-blue-400">Friday</TableHead>
          <TableHead className="text-blue-500 dark:text-blue-400">Saturday</TableHead>
          <TableHead className="text-blue-500 dark:text-blue-400">Sunday</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableCell className="text-blue-500 dark:text-blue-400">BREAKFAST (7:30 AM – 9:15 AM)</TableCell>
          <TableCell>
            Aloo pyaz parantha Ketchup, pickle Sprouts Bournvita, Coffee Bread, Butter, Jam Milk (250 mL), Tea
          </TableCell>
          <TableCell>
            Uttappam Sambhar Red Coconut Chutney Cornflakes Bournvita, Coffee Bread, Butter, Jam Milk (250 mL), Tea
          </TableCell>
          <TableCell>
            Pav Bhaji Chopped Onions Ketchup, Pickle Bournvita,Coffee Bread, Butter, Jam Milk (250 mL), Tea
          </TableCell>
          <TableCell>White Chole Poori Dalia Sprouts Bournvita, Coffee Bread, Butter, Jam Milk (250 mL), Tea</TableCell>
          <TableCell>
            Mix Parantha Ketchup, Pickle Sprouts Bournvita, Coffee Bread, Butter, Jam Milk (250 mL), Tea
          </TableCell>
          <TableCell>
            Poha Ketchup Chopped Onions Omelette/fruits (2Nos.) Bournvita, Coffee Bread, Butter, Jam Milk (250 mL), Tea
          </TableCell>
          <TableCell>
            Dosa, Sambhar Red Coconut Chutney Fruits/Boiled eggs (2 Nos.) Bournvita, Coffee Bread, Butter, Jam Milk (250
            mL), Tea
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="text-blue-500 dark:text-blue-400">LUNCH (12:30 PM – 2:15 PM)</TableCell>
          <TableCell>Veg biryani/Egg biryani Mix Raita Rice Chapati Dal – tadka Salad (Onion, Lemon)</TableCell>
          <TableCell>Rajma Pumpkin Curd (200 gm) Rice Chapati Salad (Onion, Lemon)</TableCell>
          <TableCell>Kadi pakoda Aloo Jeera Papad Jeera – Rice Chapati Salad (Cucumber, Lemon)</TableCell>
          <TableCell>Bhindi Mix Dal Curd (200 gm) Rice Chapati Salad (Cucumber, Lemon)</TableCell>
          <TableCell>Moong Dal Paneer Bhurji/ Egg Curry Curd (200 gm) Rice Chapati Salad (Cucumber, Lemon)</TableCell>
          <TableCell>
            White Chana Bhatura Aloo Capsicum Green Chutney Boondi Raita Rice Chapati Salad (Onion, Lemon)
          </TableCell>
          <TableCell>Dal Makhni Masala Beans Curd (200 gm) Rice Chapati Salad (Cucumber, Onion, Lemon)</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="text-blue-500 dark:text-blue-400">SNACKS (4:45 PM – 5:30 PM)</TableCell>
          <TableCell>Samosa (2 Nos.) Green & Red Chutney Tea</TableCell>
          <TableCell>Bread Pakoda with stuffing (2 Nos.) Green & Red Chutney Coffee</TableCell>
          <TableCell>Aloo Tikki Chat/ Aloo Tikki Matar, Namkeen (2 Nos.) Tomato, Onion Tea</TableCell>
          <TableCell>Macaroni Sauce Cold Coffee</TableCell>
          <TableCell>Chole kulche ( 2 Nos.) Chanch (1 glass)</TableCell>
          <TableCell>Noodles Coffee</TableCell>
          <TableCell>Veg Sandwich Cold Coffee</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="text-blue-500 dark:text-blue-400">DINNER (7:30 PM – 9:15 PM)</TableCell>
          <TableCell>Malai Kofta Chana Dal Rice Chapati Sweet Boondi Salad (Onion, Lemon)</TableCell>
          <TableCell>Aloo Matar Arhar Dal Rice Chapati Poori Custard Salad (Onion, Lemon)</TableCell>
          <TableCell>
            Kadhai Paneer/Kadhai Chicken Green Sabut Moong Rice Chapati Gulab Jamun (2 Nos.) Salad (Cucumber, Lemon)
          </TableCell>
          <TableCell>Dum Aloo Masoor Dal Lemon Rice Chapati Sahi Tukda (2 halves) Salad (Cucumber, Lemon)</TableCell>
          <TableCell>Matar Masala Soya Badi Pulav Chapati Rice Kheer Salad (Cucumber, Lemon)</TableCell>
          <TableCell>Mix Veg Moth dal Fried Rice Chapati Meethi Seviyan Salad (Onion, Lemon)</TableCell>
          <TableCell>
            Shahi Paneer/ Butter Chicken Black Urad Dal Tandoori Roti/ Tawa Roti Rice Ice Cream (Vanilla+Choco. Sauce/
            Butterscotch) (2 scoops) Salad (Onion, Lemon)
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>)
  );
}
