/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oToexjZdHyU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function NewEvent() {
  return (
    <div className="mr-12">
    (<div className="max-w-4xl mx-auto pr-8 my-10 p-8 bg-white shadow rounded-lg">
      <div className="flex items-center justify-between mb-10">
        <h1 className="text-4xl font-bold">Add Events</h1>
      </div>
      <div className="space-y-8">
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 1, 2024</h2>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Input
                className="flex-1 rounded-md border border-gray-200 px-4 py-2 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:border-gray-800"
                placeholder="Add a note" />
              <Button
                className="bg-gray-900 text-white px-4 py-2 hover:bg-gray-800 transition-colors"
                variant="solid">
                <PlusIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 2, 2024</h2>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Input
                className="flex-1 rounded-md border border-gray-200 px-4 py-2 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:border-gray-800"
                placeholder="Add a note" />
              <Button
                className="bg-gray-900 text-white px-4 py-2 hover:bg-gray-800 transition-colors"
                variant="solid">
                <PlusIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 3, 2024</h2>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Input
                className="flex-1 rounded-md border border-gray-200 px-4 py-2 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:border-gray-800"
                placeholder="Add a note" />
              <Button
                className="bg-gray-900 text-white px-4 py-2 hover:bg-gray-800 transition-colors"
                variant="solid">
                <PlusIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 4, 2024</h2>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Input
                className="flex-1 rounded-md border border-gray-200 px-4 py-2 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:border-gray-800"
                placeholder="Add a note" />
              <Button
                className="bg-gray-900 text-white px-4 py-2 hover:bg-gray-800 transition-colors"
                variant="solid">
                <PlusIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 5, 2024</h2>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Input
                className="flex-1 rounded-md border border-gray-200 px-4 py-2 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:border-gray-800"
                placeholder="Add a note" />
              <Button
                className="bg-gray-900 text-white px-4 py-2 hover:bg-gray-800 transition-colors"
                variant="solid">
                <PlusIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 6, 2024</h2>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Input
                className="flex-1 rounded-md border border-gray-200 px-4 py-2 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:border-gray-800"
                placeholder="Add a note" />
              <Button
                className="bg-gray-900 text-white px-4 py-2 hover:bg-gray-800 transition-colors"
                variant="solid">
                <PlusIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-4">May 7, 2024</h2>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Input
                className="flex-1 rounded-md border border-gray-200 px-4 py-2 text-sm focus:border-gray-900 focus:outline-none dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:border-gray-800"
                placeholder="Add a note" />
              <Button
                className="bg-gray-900 text-white px-4 py-2 hover:bg-gray-800 transition-colors"
                variant="solid">
                <PlusIcon className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>)
    </div>
  );
}

function ArrowLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}
